# Alternative Snowflake environment specification
# Use this if requirements.txt doesn't work in Snowflake
name: field_engineer_app
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - streamlit>=1.30.0
  - pandas>=1.3.0
  - plotly>=5.0.0
  - pip
  - pip:
    - snowflake-snowpark-python
