-- TDC Net Snowflake Demo - Table Creation
-- Creates tables for network fault data and SOP documents

USE ROLE SYSADMIN;
USE DATABASE TELCO_DEMO;
USE SCHEMA NETWORK_OPS;
USE WAREHOUSE SID_WH;

-- Network Fault Logs Table
-- Stores structured fault data from COAX and Fiber networks
CREATE OR REPLACE TABLE NETWORK_FAULTS (
    FAULT_ID VARCHAR(50) PRIMARY KEY,
    FAULT_TIMESTAMP TIMESTAMP_NTZ,
    FAULT_CODE VARCHAR(20),
    FAULT_DESCRIPTION VARCHAR(500),
    FAULT_CATEGORY VARCHAR(50),
    NETWORK_TYPE VARCHAR(20),
    EQUIPMENT_TYPE VARCHAR(100),
    LOCATION VARCHAR(100),
    SEVERITY VARCHAR(20),
    CUSTOMER_IMPACT VARCHAR(50),
    CUSTOMERS_AFFECTED INTEGER,
    SERVICE_CALLS_GENERATED INTEGER,
    RESOLUTION_TIMESTAMP TIMESTAMP_NTZ,
    RESOLUTION_TIME_HOURS FLOAT,
    FIRST_TIME_FIX BOOLEAN,
    TECHNICIAN_TYPE_REQUIRED VARCHAR(50),
    ESTIMATED_REVENUE_IMPACT FLOAT,
    PRIORITY_SCORE FLOAT
) COMMENT = 'Network fault logs from COAX and Fiber infrastructure';

-- SOP Documents Table
-- Stores technical manuals and standard operating procedures
CREATE OR REPLACE TABLE SOP_DOCUMENTS (
    DOCUMENT_ID VARCHAR(50) PRIMARY KEY,
    TITLE VARCHAR(500),
    CATEGORY VARCHAR(100),
    EQUIPMENT_TYPES ARRAY,
    FAULT_CODES ARRAY,
    CONTENT TEXT,
    DOCUMENT_VERSION VARCHAR(20) DEFAULT '1.0',
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
) COMMENT = 'Standard Operating Procedures and technical documentation';

-- Fault Classification Training Data
-- Used for Cortex Analyst model training
CREATE OR REPLACE TABLE FAULT_CLASSIFICATION_TRAINING (
    FAULT_ID VARCHAR(50),
    FEATURES OBJECT, -- JSON object with fault characteristics
    LABEL VARCHAR(50), -- Classification label (Minor, Major, Cable Fault)
    TRAINING_SET BOOLEAN DEFAULT TRUE,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Training data for fault classification model';

-- Technician Performance Metrics
-- Tracks first-time fix rates and performance by technician type
CREATE OR REPLACE TABLE TECHNICIAN_METRICS (
    METRIC_ID VARCHAR(50) PRIMARY KEY,
    TECHNICIAN_TYPE VARCHAR(50),
    LOCATION VARCHAR(100),
    FAULT_CATEGORY VARCHAR(50),
    TOTAL_JOBS INTEGER,
    FIRST_TIME_FIX_COUNT INTEGER,
    FIRST_TIME_FIX_RATE FLOAT,
    AVG_RESOLUTION_TIME_HOURS FLOAT,
    PERIOD_START DATE,
    PERIOD_END DATE,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Technician performance metrics for operational insights';

-- Equipment Reliability Data
-- Tracks equipment failure patterns for predictive maintenance
CREATE OR REPLACE TABLE EQUIPMENT_RELIABILITY (
    EQUIPMENT_ID VARCHAR(100) PRIMARY KEY,
    EQUIPMENT_TYPE VARCHAR(100),
    LOCATION VARCHAR(100),
    NETWORK_TYPE VARCHAR(20),
    INSTALLATION_DATE DATE,
    LAST_MAINTENANCE_DATE DATE,
    FAULT_COUNT_30_DAYS INTEGER,
    FAULT_COUNT_90_DAYS INTEGER,
    PREDICTED_FAILURE_RISK FLOAT,
    MAINTENANCE_PRIORITY VARCHAR(20),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Equipment reliability and predictive maintenance data';



-- Create enhanced view with derived fields
CREATE OR REPLACE VIEW VW_NETWORK_FAULTS_ENHANCED AS
SELECT 
    *,
    -- Derived fields for analytics
    DATE(FAULT_TIMESTAMP) AS CREATED_DATE,
    DATE(RESOLUTION_TIMESTAMP) AS RESOLUTION_DATE,
    (RESOLUTION_TIMESTAMP IS NOT NULL) AS IS_RESOLVED,
    (HOUR(FAULT_TIMESTAMP) BETWEEN 8 AND 17 
     AND DAYOFWEEK(FAULT_TIMESTAMP) BETWEEN 2 AND 6) AS BUSINESS_HOURS_FAULT
FROM NETWORK_FAULTS;

-- Create views for common analytics queries
CREATE OR REPLACE VIEW VW_FAULT_SUMMARY AS
SELECT 
    FAULT_CATEGORY,
    NETWORK_TYPE,
    LOCATION,
    COUNT(*) AS TOTAL_FAULTS,
    AVG(RESOLUTION_TIME_HOURS) AS AVG_RESOLUTION_TIME,
    AVG(CASE WHEN FIRST_TIME_FIX THEN 1.0 ELSE 0.0 END) AS FIRST_TIME_FIX_RATE,
    SUM(CUSTOMERS_AFFECTED) AS TOTAL_CUSTOMERS_AFFECTED,
    SUM(ESTIMATED_REVENUE_IMPACT) AS TOTAL_REVENUE_IMPACT
FROM VW_NETWORK_FAULTS_ENHANCED
WHERE IS_RESOLVED = TRUE
GROUP BY FAULT_CATEGORY, NETWORK_TYPE, LOCATION;

CREATE OR REPLACE VIEW VW_ACTIVE_FAULTS AS
SELECT 
    FAULT_ID,
    FAULT_TIMESTAMP,
    FAULT_CODE,
    FAULT_DESCRIPTION,
    FAULT_CATEGORY,
    NETWORK_TYPE,
    EQUIPMENT_TYPE,
    LOCATION,
    SEVERITY,
    CUSTOMERS_AFFECTED,
    PRIORITY_SCORE,
    TECHNICIAN_TYPE_REQUIRED,
    DATEDIFF('hour', FAULT_TIMESTAMP, CURRENT_TIMESTAMP()) AS HOURS_SINCE_FAULT
FROM VW_NETWORK_FAULTS_ENHANCED
WHERE IS_RESOLVED = FALSE
ORDER BY PRIORITY_SCORE DESC, CUSTOMERS_AFFECTED DESC;

-- Display table creation completion
SELECT 'TDC Net Demo tables created successfully!' AS STATUS;

-- Show table information
SHOW TABLES;
