-- TDC Net Snowflake Demo - Network Faults Tables and Views
-- Creates the main network faults table and enhanced view for the Streamlit apps

USE DATABASE TELCO_DEMO;
USE SCHEMA NETWORK_OPS;
USE WAREHOUSE SID_WH;

-- Create the main network faults table
CREATE OR REPLACE TABLE NETWORK_FAULTS (
    FAULT_ID VARCHAR(50) PRIMARY KEY,
    FAULT_TIMESTAMP TIMESTAMP_NTZ,
    FAULT_CODE VARCHAR(20),
    FAULT_DESCRIPTION VARCHAR(500),
    FAULT_CATEGORY VARCHAR(50),
    NETWORK_TYPE VARCHAR(50),
    EQUIPMENT_TYPE VARCHAR(100),
    LOCATION VARCHAR(100),
    SEVERITY VARCHAR(20),
    CUSTOMER_IMPACT VARCHAR(50),
    CUSTOMERS_AFFECTED INTEGER,
    SERVICE_CALLS_GENERATED INTEGER,
    RESOLUTION_TIMESTAMP TIMESTAMP_NTZ,
    RESOLUTION_TIME_HOURS FLOAT,
    FIRST_TIME_FIX BOOLEAN,
    TECHNICIAN_TYPE_REQUIRED VARCHAR(50),
    ESTIMATED_REVENUE_IMPACT FLOAT,
    PRIORITY_SCORE FLOAT,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Main table storing network fault incidents and their resolution data';

-- Create enhanced view with calculated fields for Streamlit apps
CREATE OR REPLACE VIEW VW_NETWORK_FAULTS_ENHANCED AS
SELECT 
    -- Base fields
    FAULT_ID,
    FAULT_TIMESTAMP,
    FAULT_CODE,
    FAULT_DESCRIPTION,
    FAULT_CATEGORY,
    NETWORK_TYPE,
    EQUIPMENT_TYPE,
    LOCATION,
    SEVERITY,
    CUSTOMER_IMPACT,
    CUSTOMERS_AFFECTED,
    SERVICE_CALLS_GENERATED,
    RESOLUTION_TIMESTAMP,
    RESOLUTION_TIME_HOURS,
    FIRST_TIME_FIX,
    TECHNICIAN_TYPE_REQUIRED,
    ESTIMATED_REVENUE_IMPACT,
    PRIORITY_SCORE,
    
    -- Calculated fields
    CASE 
        WHEN RESOLUTION_TIMESTAMP IS NOT NULL THEN TRUE 
        ELSE FALSE 
    END AS IS_RESOLVED,
    
    CASE 
        WHEN HOUR(FAULT_TIMESTAMP) BETWEEN 8 AND 17 
             AND DAYOFWEEK(FAULT_TIMESTAMP) BETWEEN 1 AND 5 THEN TRUE
        ELSE FALSE
    END AS BUSINESS_HOURS_FAULT,
    
    DATEDIFF('hour', FAULT_TIMESTAMP, COALESCE(RESOLUTION_TIMESTAMP, CURRENT_TIMESTAMP())) AS HOURS_SINCE_FAULT,
    
    DATE(FAULT_TIMESTAMP) AS FAULT_DATE,
    DATE(RESOLUTION_TIMESTAMP) AS RESOLUTION_DATE,
    
    CASE 
        WHEN PRIORITY_SCORE > 0.8 THEN 'CRITICAL'
        WHEN PRIORITY_SCORE > 0.6 THEN 'HIGH'
        WHEN PRIORITY_SCORE > 0.4 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS RISK_LEVEL,
    
    CASE 
        WHEN FAULT_CATEGORY = 'Cable Fault' AND HOURS_SINCE_FAULT > 4 THEN TRUE
        WHEN FAULT_CATEGORY = 'Major' AND HOURS_SINCE_FAULT > 2 THEN TRUE
        WHEN FAULT_CATEGORY = 'Minor' AND HOURS_SINCE_FAULT > 1 THEN TRUE
        ELSE FALSE
    END AS SLA_BREACH_RISK,
    
    CREATED_TIMESTAMP,
    UPDATED_TIMESTAMP
    
FROM NETWORK_FAULTS
COMMENT = 'Enhanced view of network faults with calculated fields for Streamlit applications';

-- Create sample data for demo purposes
INSERT INTO NETWORK_FAULTS (
    FAULT_ID, FAULT_TIMESTAMP, FAULT_CODE, FAULT_DESCRIPTION, FAULT_CATEGORY,
    NETWORK_TYPE, EQUIPMENT_TYPE, LOCATION, SEVERITY, CUSTOMER_IMPACT,
    CUSTOMERS_AFFECTED, SERVICE_CALLS_GENERATED, RESOLUTION_TIMESTAMP,
    RESOLUTION_TIME_HOURS, FIRST_TIME_FIX, TECHNICIAN_TYPE_REQUIRED,
    ESTIMATED_REVENUE_IMPACT, PRIORITY_SCORE
) VALUES
('F001', '2024-01-15 08:30:00', '812.3', 'Cable signal degradation in residential area', 'Cable Fault', 'HFC', 'Cisco cBR-8', 'Copenhagen North', 'High', 'Service Degradation', 150, 12, '2024-01-15 12:45:00', 4.25, TRUE, 'Senior Technician', 25000, 0.85),
('F002', '2024-01-15 14:20:00', '813.1', 'Amplifier failure causing signal loss', 'Major', 'HFC', 'Arris E6000', 'Aarhus Central', 'Critical', 'Service Outage', 300, 45, NULL, NULL, FALSE, 'Expert Technician', 75000, 0.95),
('F003', '2024-01-15 16:45:00', '814.2', 'Minor interference on upstream channel', 'Minor', 'DOCSIS', 'Casa C100G', 'Odense West', 'Low', 'Performance Issue', 25, 3, '2024-01-15 17:30:00', 0.75, TRUE, 'Junior Technician', 2500, 0.35),
('F004', '2024-01-16 09:15:00', '815.5', 'Fiber cut affecting business district', 'Cable Fault', 'Fiber', 'Nokia 7750', 'Copenhagen Business', 'Critical', 'Service Outage', 500, 85, NULL, NULL, FALSE, 'Expert Technician', 150000, 0.98),
('F005', '2024-01-16 11:30:00', '816.1', 'CMTS overload during peak hours', 'Major', 'DOCSIS', 'Cisco cBR-8', 'Aalborg North', 'High', 'Service Degradation', 200, 25, '2024-01-16 15:20:00', 3.83, FALSE, 'Senior Technician', 40000, 0.78);

-- Verify the data and view
SELECT COUNT(*) AS TOTAL_FAULTS FROM NETWORK_FAULTS;
SELECT COUNT(*) AS ENHANCED_VIEW_COUNT FROM VW_NETWORK_FAULTS_ENHANCED;

-- Show sample enhanced data
SELECT 
    FAULT_ID,
    FAULT_TIMESTAMP,
    FAULT_CATEGORY,
    IS_RESOLVED,
    BUSINESS_HOURS_FAULT,
    HOURS_SINCE_FAULT,
    RISK_LEVEL,
    SLA_BREACH_RISK
FROM VW_NETWORK_FAULTS_ENHANCED 
LIMIT 5;
